### ISSUE TITLE
Compiler XMRig

### ISSUE THREAD

**Issue by tsaquet** [ideaprod/minergift#2]

**Comment by EmilienBertin** [comment]
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/api/Httpd.cpp.o
[100%] Linking CXX executable xmrig
[100%] Built target xmrig
[embertin@VbFedora]~/MinerGift/xmrig/build% ll
total 1708
-rw-rw-r--. 1 embertin embertin   13758 23 nov.  13:50 CMakeCache.txt
drwxrwxr-x. 5 embertin embertin    4096 23 nov.  13:51 CMakeFiles
-rw-rw-r--. 1 embertin embertin    1573 23 nov.  13:50 cmake_install.cmake
-rw-rw-r--. 1 embertin embertin   39288 23 nov.  13:50 Makefile
drwxrwxr-x. 3 embertin embertin    4096 23 nov.  13:50 src
-rwxrwxr-x. 1 embertin embertin 1676664 23 nov.  13:51 **xmrig**


C'est fait sous Fedora.
Et j'arrive à miner (du Monero) sur MinerGate avec le client créé.

**Comment by EmilienBertin** [comment]
@tsaquet Est-ce que je compile aussi sous Windows ?

**Comment by tsaquet** [comment]
C'est une super nouvelle ça !
Oui sous Windows, c'est quand même notre cible principale ;p

**Comment by EmilienBertin** [comment]
C'est bon : 
[ 88%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_groestl.c.obj
[ 91%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_blake256.c.obj
[ 93%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_jh.c.obj
[ 95%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_skein.c.obj
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/CryptoNight.cpp.obj
[100%] Linking CXX executable xmrig.exe
[100%] Built target xmrig

embertin@EMBERTIN-WS MINGW64 ~/MinerGift/xmrig/build
$ ls
cmake_install.cmake  CMakeCache.txt  CMakeFiles  Makefile  src  **xmrig.exe**


Par contre j'ai du faire quelques changements dans le build. 
A discuter : cf bug https://github.com/xmrig/xmrig/issues/142
Ma ligne de build :  cmake .. -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:/msys64/mingw64/include" -DUV_LIBRARY="c:/msys64/mingw64/lib/libuv.a"  -DWITH_HTTPD=OFF

**Comment by EmilienBertin** [comment]
Changement dans xmrig cf issue #12
