### ISSUE TITLE
Graphisme

### ISSUE THREAD

**Issue by tsaquet** [ideaprod/minergift#22]
Icone
Bouton
Etc

**Comment by EmilienBertin** [comment]
Quelques points supplémentaires :
- Utiliser le terme application et pas logiciel
- Dans la UI, avoir un retour sur le minage en cours (quantité déjà minée, montant en euros ?)

**Comment by EmilienBertin** [comment]
Graphisme ok pour le MVP.
Pour le retour du travail déjà effectué, pas MVP, on ouvrira une autre issue.
